name = input('What is your name: ')
aboutUser = input('In a sentence describe yourself: ')
page = open('page.html', 'w')
page.write('<!DOCTYPE html>\n')
page.write('<html>\n')
page.write('<body>\n')
page.write('\t<center>\n')
page.write(f'\t\t<h1>{name}</h1>\n')
page.write('\t</center>\n')
page.write('\t<hr />\n')
page.write(f'\t{aboutUser}\n')
page.write('\t<hr />\n')
page.write('</body>\n')
page.write('</html>\n')
page.close()